POST  http://localhost:3000/users/get-user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5NDQxODkzNzMyMTQ3MjAwMDEiLCJpYXQiOjE3MDg2MzkxNzYsImV4cCI6MTcwODcyNTU3Nn0.ShCURiPKUBwcgOIxhaSTlguZL2Et5BTob0BUwL6QJ9o


